apps/blog/urls.py
from django.urls import path
from .views import (posts, post_detail, 
                    post_share, post_comment,
                    search
                    )


urlpatterns = [
    path('posts/',posts, name='posts'),
    path('post/<int:id>/',post_detail, name='post_detail'),
    path('<int:id>/share', post_share, name='post_share'),

    path('<int:id>/comment', post_comment, name='post_comment'),
    path('posts/<int:tag_id>', posts, name='tag_page'),

    path('search/', search,name='search'),
    

]

devblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),   
    path('__debug__/', include('debug_toolbar.urls')),   
    path('devblog/', include(('apps.blog.urls', 'blog'), namespace='blog')),
]
                       

templates/devblog/posts/comment.html
{% extends 'devblog/base.html' %}

{% block title %}Comment{% endblock title %}

{% block content %}
    {% if comment is not None %}
        <h3>Your comment has been added</h3>
        <p><a href="{{post.get_absolute_url}}">Back To Post</a></p>
    {% else %}
        {% include 'devblog/posts/includes/comment_form.html' %}
    {% endif %}
{% endblock content %}

templates/devblog/posts/detail.html
{% extends 'devblog/base.html' %}

{% block title %}Post-{% endblock title %}

{% block content %}

<div>
    <h1>{{post.title}}</h1>
    <p>{{post.body}}</p>
    {% for tag in tags %}
        <h5>{{tag.name}}</h5>
    {% endfor %}
    <div>
        <p><a href="{% url 'blog:post_share' post.id %}">Share Post Via E-mail</a></p>
    </div>
    <div>
        {% with comments.count as total_comments %}
            <h3>{{total_comments}} comment{{total_comments|pluralize}} </h3>
        {% endwith %}
    </div>

    <div>
        <h3>Similar Posts</h3>
        {% for sim_post in similar_posts %}
            <p><a href="{% url 'blog:post_detail' sim_post.id %}">{{sim_post.title}}</a></p>
            {% empty %}
            <p>There are no similar posts yet</p>
        {% endfor %}
        
    </div>
    <div>
        {% for comment in comments %}
            <p>{{comment.title}}</p>
            <p>{{comment.body}}</p>
        {% endfor %}
    </div>
    {% include 'devblog/posts/includes/comment_form.html' %}
</div>



{% endblock content %}

templates/devblog/posts/list.html
{% extends 'devblog/base.html' %}

{% block title %}Posts{% endblock title %}

{% block content %}
    
<h2>Avalable Tags</h2>
        <p><a href="{% url 'blog:posts' %}">All</a></p>
        {% for tag in tags %}
        <p><a href="{% url 'blog:tag_page' tag.id %}">{{tag.name}}</a></p>
        {% endfor %}
    <h2>All Posts</h2>

        {% for post in posts %}
            <h4><a href="{{post.get_absolute_url}}">{{post}}</a></h4>
        {% endfor %}
        {% include 'devblog/pagination.html' with page=posts %}
{% endblock content %}

templates/devblog/posts/search.html
{% extends 'devblog/base.html' %}

{% block title %}Search{% endblock title %}

{% block content %}

<div>
    <form method="GET" >
        {{form}}
        <input type="submit" value="Search">
    </form>

    {% if query %}
        20 Posts found for "{{query}}"
        {% for post in results %}
            <p>{{post.title}}</p>
            <p>{{post.body}}</p>
        {% empty %}
            <h3>No Posts found for "{{query}}"</h3>
        {% endfor %}
    {% endif %}  
</div>
{% endblock content %}

templates/devblog/posts/share.html
{% extends 'devblog/base.html' %}

{% block title %}Share Post via E-mail{% endblock title %}

{% block content %}
    {% if sent %}
        <h3>{{post.title}} Successfully sent to {{form.cleaned_data.to}}</h3>
        <p><a href="{{post.get_absolute_url}}">Back To Post</a></p>
    {% else %}
    <h2>Share {{post.title}} by e-mail</h2>
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Share Post">
    </form>
    {% endif %}
        
{% endblock content %}